version: '2'
services:
  ns2:
    image: ns2
    container_name: ns2
    hostname: ns2.fqdn
    build: .
    volumes:
      - ./etc:/etc/bind9
    network_mode: "bridge"
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    restart: unless-stopped

